### ISSUE TITLE
Ti 3.5.0 Alpha?

### ISSUE THREAD

**Issue by kosso** [ludolphus/AviaryModule#8]
Hi there! 

Have you been able to get this running on the Ti 3.5.0 Alpha? By February, *all* modules need to be updated for 64bit support. 

See: http://www.appcelerator.com/blog/2014/11/alpha-version-of-titanium-sdk-64-bit-support-now-available

**Comment by ludolphus** [comment]
I'm waiting for the 3.5 release, don't want to 'waste' too much time with beta's and RCs

**Comment by ludolphus** [comment]
updated 64-bit module now available, uses Aviary SDK 4.2.0

**Comment by kosso** [comment]
:+1:
