### ISSUE TITLE
Adobe now owns Aviary, so how do I specify the Key & Secret?

### ISSUE THREAD

**Issue by bwilhelm** [ludolphus/AviaryModule#9]
In your code you specify this:

aviary.newImageEditor({apikey:'[KEY]', secret: '[SECRET]', image: img, tools: tools});

When I create an app on the Adobe Creative SDK site, it only gives me a 'secret' and a Client ID - no API key is given, so how do I obtain that?

I have tried the Client ID as the API key, and I get an invalid API key message.

**Comment by bwilhelm** [comment]
So after a bit of Googling, I found this:

https://creativesdk.zendesk.com/hc/en-us/articles/202903359-Migrating-from-the-Aviary-SDK-to-the-Adobe-Creative-SDK-Beta

"Your old Aviary Api Key will no longer work with the Creative SDK, so you’ll need to create a new App ID on the My Apps page on CreativeSDK.com. Note: make sure you write down your Secret since you won’t be able to retrieve it after registering your app."

So unless you have an old Aviary API key, this module won't work until its updated to pass in the Client ID and also references the Adobe Creative SDK instead of the Aviary SDK.

**Comment by ludolphus** [comment]
please check out this module https://github.com/kosso/TiAdobeCreativeSDK which is based on the the work I (and others) did here.
